language: python
python:
- "3.7"
- "pypy3"
install:
- python -m pip install --upgrade pip
- python -m pip install --editable .[dev]
script:
# TODO: Figure out anonymous bind credentials for dockerhub API and change to "args=--allow-online make test"
- make test
